Implemented the CDS Term for H2O
grimme-lab/numsa pull request #2
Opened 2021-05-31 17:02 UTC by MtoLStoN

This Implements default Parameters for H2O and the Ability to calculate the CDS term of the SMD Model for Water. (numsa coord -s h2o)

2021-06-01 15:29 UTC, MtoLStoN commented
Should work now with default SMD Parameters for DMSO, Methanol, Acetonitrile and H2O. Also adds the possibility to use any Solvent by adding a property file *.prop into the working directory. Adding own Parameters for the SMD for Fitting Purposes etc. will follow in another Pull Request.

2021-06-13 14:25 UTC, awvwgk requested changes
Thanks, this looks overall well done, but I'm missing at least some testing. Can you add some regression testing for this new feature in the `test` subdirectory?

Gradients would be nice as well, but we can look into this separately.

2021-06-15 09:25 UTC, awvwgk approved these changes
Thanks, look good now.

2021-06-15 09:25 UTC, awvwgk commented on app/main.f90
> +      Call ascii_cds(output_unit,mol,cds,cds_sm)
```suggestion
      call init_smd(param,config%solvent)
      call calc_surft(mol%xyz,mol%id,mol%sym,param,surft)
      call calc_cds(surft,surface,mol%sym,mol%id,cds,cds_sm)
      call ascii_cds(output_unit,mol,cds,cds_sm)
```

2021-06-15 09:25 UTC, awvwgk commented on test/test_cds.f90
> +
```suggestion
```

2021-06-15 09:31 UTC, merged